---
namespace: geerlingguy
name: php_roles
description: An elegant collection of roles for PHP automation.
version: "1.0.0"
readme: README.md

authors:
  - geerlingguy (https://www.jeffgeerling.com/)

license:
  - MIT

tags:
  - php
  - apache
  - lamp
  - lemp
  - nginx
  - apache
  - debian
  - ubuntu
  - centos
  - amazon
  - linux
  - rhel
  - fedora
  - drupal
  - wordpress
  - laravel

dependencies:
  community.general: ">=3.0.0"

repository: https://github.com/geerlingguy/ansible-collection-php_roles
documentation: https://github.com/geerlingguy/ansible-collection-php_roles
homepage: https://www.jeffgeerling.com
issues: https://github.com/geerlingguy/ansible-collection-php_roles/issues

build_ignore:
  - scripts
  - tests
  - .DS_Store
